# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
pr:
- master

pool:
  vmImage: 'windows-2019'

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false

- task: Npm@0
  displayName: 'install typescript'
  inputs:
    arguments: 'typescript@2.8.1 --global-style'

- task: Npm@0
  displayName: 'install tfx-cli command'
  inputs:
    arguments: 'tfx-cli@v0.7.6 --global'

- task: CmdLine@2
  inputs:
    workingDirectory: $(Build.SourcesDirectory)/src
    script: |
      npm install

- task: CmdLine@2
  inputs:
    workingDirectory: $(Build.SourcesDirectory)/src
    script: |
      tsc

- task: CmdLine@2
  inputs:
    workingDirectory: $(Build.SourcesDirectory)
    script: |
      tfx extension create --manifest-globs vss-extension.json

- task: CmdLine@2
  inputs:
    workingDirectory: $(Build.SourcesDirectory)
    script: |
      tfx extension create --manifest-globs vss-extension.json

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**/*.vsix'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'

