# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
pr:
- master

pool:
  vmImage: 'windows-2019'

stages:

- stage: build
  displayName: Build vsix packages
  jobs:
    - job: build
      steps:
      - task: Npm@1
        displayName: 'npm install'
        inputs:
          verbose: false

      - task: Npm@0
        displayName: 'install typescript'
        inputs:
          arguments: 'typescript@2.8.1 --global-style'

      - task: Npm@0
        displayName: 'install tfx-cli command'
        inputs:
          arguments: 'tfx-cli@v0.7.6 --global'

      - task: CmdLine@2
        inputs:
          workingDirectory: $(Build.SourcesDirectory)/src
          script: |
            npm install

      - task: CmdLine@2
        inputs:
          workingDirectory: $(Build.SourcesDirectory)/src
          script: |
            tsc

      - task: CmdLine@2
        inputs:
          workingDirectory: $(Build.SourcesDirectory)
          script: |
            tfx extension create --publisher rdagumampan --manifest-globs vss-extension.json --output-path vsix-public
      - task: CmdLine@2
        inputs:
          workingDirectory: $(Build.SourcesDirectory)
          script: |
            tfx extension create --publisher rdagumampandev --manifest-globs vss-extension.json --output-path vsix-private
    
      - task: CopyFiles@2
        displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
        inputs:
          SourceFolder: '$(Build.SourcesDirectory)'
          Contents: '**/*.vsix'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: drop'

- stage: publishPrivate
  displayName: Publish to private marketplace
  dependsOn: build
  jobs:
    - deployment: private

      environment: az-marketplace-private

      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self

            # - task: NodeTool@0
            #   displayName: 'Use Node 6.x'

            - task: CmdLine@2
              inputs:
                workingDirectory: $(Build.SourcesDirectory)
                script: |
                  cd $(Build.ArtifactStagingDirectory)
                  dir

            # - task: ms-devlabs.vsts-developer-tools-build-tasks.publish-extension-build-task.PublishAzureDevOpsExtension@2
            #   displayName: 'Publish Extension'
            #   inputs:
            #     connectedServiceName: 'az-marketplace'
            #     fileType: vsix
            #     vsixFile: '$(Build.ArtifactStagingDirectory)/drop/*.vsix'
            #     extensionVersion: '0.$(Release.ReleaseId).0'
            #     extensionVisibility: private
            #     extensionPricing: free
            #     bypassLocalValidation: true
            #     noWaitValidation: true

- stage: publishPublic
  dependsOn: publishPrivate
  displayName: Publish to public marketplace
  jobs:
    - deployment: private

      environment: az-marketplace-public

      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self

